#+title: Project Milestone 2
#+author: Team Lithium

* Info

For simplicity of setup/build, we are using SQLite, since it works nicely ootb with no setup outside of Python script.

* Setup

** Python Version

Ensure you are using at minimum python version 3.12.

This is the most widely-adopted of the recent python version. It has some nice features that make writing this code much better.

#+begin_src bash
python3 --version
#+end_src

** Dependencies

It is recommended that you use a virtual environment before continuing. This project was built using `uv` as it handles most of the annoying project config, but any venv will work.

To setup a venv with `uv`:

#+begin_src bash
uv venv
#+end_src

Remember to activate the venv afterwards using the command it spits back at you. On Linux this is simply:

#+begin_src bash
source .venv/bin/active
#+end_src

Install the project requirements:

#+begin_src bash
uv pip install -r requirements.txt
#+end_src

And you are ready to go.

* Running the Project

** First Run

On your first run, you should initialize the database:

#+begin_src bash
python3 main.py --init
#+end_src

This creates a database file called ~library.db~, which we will query with sqlite. There is a way to do this from the in-app settings, but this quicker on first run.

** Normal Operation

#+begin_src bash
python3 main.py
#+end_src

It should open up a GUI/TUI in your terminal. To run it in the brower:

#+begin_src bash
textual serve main.py
#+end_src

and open the corresponding port in your browser.

** Resetting Progress

To run the initialization step AND DELETE THE CURRENT DB (eg. to start fresh), pass ~--init -f~ to force initialization. Or, alternatively, do this from the settings menu in-app.

#+begin_src bash
python3 main.py --init -f
#+end_src

You could also just delete the file and run ~--init~ again, but this way is nicer.

WARNING: this removes all progress from created borrowers, checkouts, fines, etc. and just starts fresh with the given data.
