
BOOKS_TABLE_NAME = 'BOOK'
BOOK_AUTHORS_TABLE_NAME = 'BOOK_AUTHORS'
AUTHORS_TABLE_NAME = 'AUTHORS'
BORROWERS_TABLE_NAME = 'BORROWER'
BOOK_LOANS_TABLE_NAME = 'BOOK_LOANS'
FINES_TABLE_NAME = 'FINES'
METADATA_TABLE_NAME = 'metadata'
